//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internetProgramciligiFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string surName { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string skill { get; set; }
        public string gender { get; set; }
        public string image { get; set; }
        public string isItWorking { get; set; }
        public Nullable<int> salary { get; set; }
        public string socialMedya { get; set; }
        public string e_mail { get; set; }
        public string projes { get; set; }
        public string pNumber { get; set; }
    }
}
